"""Data structures and models for PanduGizi Convergent AI architecture."""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any


@dataclass
class TriggerReason:
    """Represents a specific deterministic clinical or administrative trigger."""
    rule: str
    reason: str
    weight: int
    evidence: Dict[str, Any] = field(default_factory=dict)
    reason_id: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "rule": self.rule,
            "reason": self.reason,
            "weight": self.weight,
            "evidence": self.evidence,
            "reason_id": self.reason_id,
        }


@dataclass
class PatientProfile:
    """Clinical and administrative profile of a maternal or child patient."""
    id: str
    nama: str
    kategori: str  # 'ibu hamil' or 'balita'
    lila: Optional[float] = None  # cm for pregnant mothers
    status_gizi: Optional[str] = None  # e.g., 'normal', 'berisiko', 'stunting', 'gizi buruk'
    tinggi_badan: Optional[float] = None
    berat_badan: Optional[float] = None
    has_active_complaint: bool = False
    complaint_description: Optional[str] = None
    complaint_severity: Optional[str] = "none"  # 'none', 'mild', 'moderate', 'severe'
    complaint_category: Optional[str] = None
    days_since_last_monitoring: Optional[int] = None  # None means no monitoring recorded
    latest_monitoring_risk: bool = False
    missed_medication_today: bool = False
    missed_pmt_today: bool = False
    monitoring_history: List[Dict[str, Any]] = field(default_factory=list)
    complaint_history: List[Dict[str, Any]] = field(default_factory=list)

    @property
    def is_pregnant(self) -> bool:
        return "hamil" in self.kategori.lower()

    @property
    def is_toddler(self) -> bool:
        cat = self.kategori.lower()
        return "balita" in cat or "anak" in cat


@dataclass
class ScoringResult:
    """Result of Stage 1 deterministic rule-based triage scoring."""
    priority_score: int
    priority_level: str  # 'low', 'medium', 'high'
    trigger_reasons: List[TriggerReason]
    rules_evaluated: List[str]
    patient_category: str

    def to_dict(self) -> Dict[str, Any]:
        return {
            "priority_score": self.priority_score,
            "priority_level": self.priority_level,
            "trigger_reasons": [r.to_dict() for r in self.trigger_reasons],
            "rules_evaluated": self.rules_evaluated,
            "patient_category": self.patient_category,
        }


@dataclass
class DualOutput:
    """Dual outputs synthesized by Stage 2 or generated by Stage 3 fallback."""
    recommended_action: str
    whatsapp_message: str
    source: str  # 'llm_agent' or 'graceful_fallback'
    latency_ms: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "recommended_action": self.recommended_action,
            "whatsapp_message": self.whatsapp_message,
            "source": self.source,
            "latency_ms": self.latency_ms,
        }


@dataclass
class PipelineResult:
    """Complete end-to-end result of Algorithm 1 Convergent AI pipeline."""
    patient_id: str
    patient_name: str
    patient_category: str
    priority_score: int
    priority_level: str
    trigger_reasons: List[TriggerReason]
    recommended_action: str
    whatsapp_message: str
    synthesis_source: str  # 'llm_agent' or 'graceful_fallback'
    latency_ms: float
    verified_by_clinician: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "patient_id": self.patient_id,
            "patient_name": self.patient_name,
            "patient_category": self.patient_category,
            "priority_score": self.priority_score,
            "priority_level": self.priority_level,
            "trigger_reasons": [r.to_dict() for r in self.trigger_reasons],
            "recommended_action": self.recommended_action,
            "whatsapp_message": self.whatsapp_message,
            "synthesis_source": self.synthesis_source,
            "latency_ms": self.latency_ms,
            "verified_by_clinician": self.verified_by_clinician,
        }
